### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by fumiya-yoshii** [fumiya-yoshii/protospace-395620-d#1]
自身のProtoSpaceのURL（本番環境）
https://protospace-395620-d.onrender.com

**Comment by shodai-ito** [comment]
@fumiya-yoshii さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
アプリの使用上、ユーザー名には敬称まで表示をお願いします。
<img width="482" alt="スクリーンショット 2023-07-24 17 59 29" src="https://github.com/fumiya-yoshii/protospace-395620-d/assets/62537107/7f59f782-3f1c-416c-b9f9-79e0ad87a6af">

- [x] **プロトタイプの名称・キャッチコピー・コンセプトが必須であること**
画像があれば投稿できてしまいます。

- [x] **投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まること**
全て空欄で投稿しようとすると、ページに留まらずトップページに遷移してしまいます。

- [x] **ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されていること**
投稿主以外のユーザーがプロトタイプ詳細ページに遷移すると、画像が表示されません。

- [x] **空の入力欄がある場合は、編集できずにそのページに留まること**
投稿の時と同様、画像以外が空欄でも編集できてしまいます。

- [x] **正しく編集できた場合は、詳細ページへ遷移すること**
詳細ページでなく、トップページに遷移してしまいます。

- [x] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できること**
コメント済みのプロトタイプを削除しようとするとエラーになります。

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
プロトタイプ詳細ページのプロトタイプ投稿者名、及びコメント投稿者名をクリックしても、該当ユーザーの詳細ページに遷移できません。
<img width="480" alt="スクリーンショット 2023-07-24 18 01 36" src="https://github.com/fumiya-yoshii/protospace-395620-d/assets/62537107/c08b0237-9332-4cc5-87e0-279a69c205ab">
<img width="348" alt="スクリーンショット 2023-07-24 18 01 40" src="https://github.com/fumiya-yoshii/protospace-395620-d/assets/62537107/3166882c-7722-4019-9ab0-4374988d3cea">

- [x] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できること**
ログアウト状態では全てのページにアクセスできない状態になっています。

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他人のプロトタイプ編集ページに遷移できてしまいます。
【チェック方法】
先ず、ユーザーAで投稿したプロトタイプの編集ページURLをコピー。
次に、ユーザーBでログインし、そのURLを直接入力した際に、トップページへリダイレクトされれば正常な挙動。

修正が完了しましたら、**必ず一度ご自身の本番環境で正しく動作しているか確認**してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by fumiya-yoshii** [comment]
再度訂正しました。

**Comment by mo1015** [comment]
再提出ありがとうございます‼︎
動作の確認をしたところ、引き続き修正が必要な箇所と、新たに修正いただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

`プロトタイプ一覧表示機能`

- [x] **ログイン・ログアウトの状態に関わらず、プロトタイプ一覧を閲覧できること**
ログアウト状態で閲覧できません。

`ユーザー詳細機能`

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
コメントの投稿者名をクリックしても、該当ユーザーの詳細ページに遷移できません。（そのプロトタイプを投稿したユーザーの詳細ページへ遷移してしまいます）

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
所属・役職が正しく表示されていません。（所属の欄に役職として入力した情報が、役職の欄に所属として入力した情報が表示されています）

`その他
`
- [x] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できること**
トップページ・プロトタイプ詳細ページへ遷移できません。

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他人のプロトタイプ編集ページに遷移できてしまいます。
【チェック方法】
先ず、ユーザーAで投稿したプロトタイプの編集ページURLをコピー。
次に、ユーザーBでログインし、そのURLを直接入力した際に、トップページへリダイレクトされれば正常な挙動。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by fumiya-yoshii** [comment]
訂正しました。

**Comment by mo1015** [comment]
再提出ありがとうございます‼︎
動作の確認をしたところ、再度修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他のユーザーのプロトタイプ編集ページに遷移できてしまいます。トップページへ遷移するよう修正をお願いします。

https://github.com/fumiya-yoshii/protospace-395620-d/assets/62644781/772892bf-bcb7-49bb-bb81-97825baf8a90



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by fumiya-yoshii** [comment]
完了しました

**Comment by snkw-works** [comment]
@fumiya-yoshii さん、ご提出ありがとうございます‼︎
修正が確認でき、正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

今後の学習は、担当ライフコーチとご相談のうえ進めてください。
